version: '3'
services:
  app:
      image: 'vopgh0409/docker-memo:latest'
      ports:
        - "80:3000"
  db:
    image: 'mysql:5.7'
    container_name: node_mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=hanghea99
      - MYSQL_DATABASE=development
      - TZ=Asia/Seoul
    ports:
      - "3306:3306"
    command:
      - --character-set-server=utf8 
      - --collation-server=utf8_unicode_ci
